project:
  type: website

website:
  title: "Sneha's Blogs"
  navbar:
    background: success
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-snehakharbanda
format:
  html:
    theme: journal



